### ISSUE TITLE
Where Can I find documentation

### ISSUE THREAD

**Issue by CosmicFusion** [hkoosha/zoha-vte4#1]
I cannot find any form of documentation for neither this fork, or the original vte4-rs

Where can I find them?

https://malureau.pages.gitlab.gnome.org/vte4-rs/stable/latest/docs/vte4

Has been down for over 5 months

**Comment by hkoosha** [comment]
Hi!

Unfortunately I did not find any documentations either, I just hacked my way through it. Since I was hoping that the original project in the GNOME repository to be updated, I did not focus much on doign things the right way either :(

**Comment by CosmicFusion** [comment]
> Hi!
> 
> Unfortunately I did not find any documentations either, I just hacked my way through it. Since I was hoping that the original project in the GNOME repository to be updated, I did not focus much on doign things the right way either :( 

Can you give an example code snippet of spawing a vte

I'll find a way to make work of just that eventually 

:(

**Comment by CosmicFusion** [comment]
This seems to be the issue on why we don't have docs

https://docs.rs/crate/vte4/latest

And it's 2 open issues on their gitlab, but gnome isn't responding to them for over 5 month

Maybe this project can fix the docs.rs build issue

**Comment by hkoosha** [comment]
Please have a look at https://github.com/hkoosha/zoha4, specially [this line](https://github.com/hkoosha/zoha4/blob/917c906b05f335753496b289a0eafa781a506fe2/src/ui/terminal.rs#L214):

The trick is to call `spawn_async()` on a VTE struct, else you'll get a blank terminal. Took me a while to figure this out. Please note the `async` has nothing to do with rust's async support, it just `C` stuff, expecting a callback fn.

**Comment by CosmicFusion** [comment]
> This seems to be the issue on why we don't have docs
> 
> https://docs.rs/crate/vte4/latest
> 
> And it's 2 open issues on their gitlab, but gnome isn't responding to them for over 5 month
> 
> Maybe this project can fix the docs.rs build issue

Build logs show that this is just dependencies not being installed


I think it's easy AF to fix they just don't wanna do it

**Comment by hkoosha** [comment]
I think there's little interest in VTE for rust right now, hence no support or maintenance.

**Comment by CosmicFusion** [comment]
> Please have a look at https://github.com/hkoosha/zoha4, specially [this line](https://github.com/hkoosha/zoha4/blob/917c906b05f335753496b289a0eafa781a506fe2/src/ui/terminal.rs#L214):
> 
> The trick is to call `spawn_async()` on a VTE struct, else you'll get a blank terminal. Took me a while to figure this out. Please note the `async` has nothing to do with rust's async support, it just `C` stuff, expecting a callback fn.

<3

**Comment by CosmicFusion** [comment]
I have submitted a fix MR to vte4-rs let's hope the gnome isn't lazy enough to not accept a free fix

https://gitlab.gnome.org/World/Rust/vte4-rs/-/merge_requests/5
